spring:
  datasource:
    url: jdbc:postgresql://localhost:6001/postgres
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always

  security:
    user:
      name: guest
      password: french

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

